### PR TITLE
Updated to add webpack deployment process.

### LINKED ISSUE #15: Unable to install via webpack
The package is missing all the au-*.js files

### PR DESCRIPTION
**Pull request by evenflow58**
Resolves #15 

You might want to ignore the bundle.js and set up the webpack command on your build (it's just webpack).

### CODE REVIEW

**Comment by tochoromero** [comment]
Thank you very much for the pull request.
I have never used webpack so I know very little of how it works, it seems you are just adding some configuration that is specific for web pack.
I assume this will have no effect if you are using JSPM or Aurelia CLI, right?

**Comment by evenflow58** [comment]
Not to my knowledge. I quickly moved away from JSPM because of scalability issues and Aurelia CLI does not seem production ready. I'm still learning webpack myself. It shouldn't affect any of that unless they are looking at bundle.js, which I doubt they are since you didn't have it in your repo before.

**Comment by evenflow58** [comment]
Doing some more testing and I found that this fork does not actually fix the problem. Users can update the aurelia > build > resources portion of package.json to pull in the files but that is not ideal. If I have time I'll try and work on creating a webpack bundle for this.

**Comment by tochoromero** [comment]
Thank you very much I appreciate it

**Comment by evenflow58** [comment]
Closing this pull request as @ds2co got it to work.

**Pull request closed without merging**
