### PR TITLE
Update package.json

### LINKED ISSUE #15: Unable to install via webpack
The package is missing all the au-*.js files

### PR DESCRIPTION
**Pull request by ds2co**
update to make package work with webpack
resolves #15

### CODE REVIEW

**Comment by tochoromero** [comment]
Would you please give me a little bit of context on how this is working?

**Comment by ds2co** [comment]
The aurelia build resources addition to the package.json file tells aurelia-webpack to resolve those paths in the main file before bundling.

**Comment by tochoromero** [comment]
I see, that makes sense, thanks for the contribution.

**Comment by ds2co** [comment]
can you cut a patch release for this? thanks

**Comment by tochoromero** [comment]
Yes, I will do it right now

**Comment by tochoromero** [comment]
Done :)

**Comment by ds2co** [comment]
thank you :)

**Pull request merged**
